const candidates = [
  { name: "Monkey D. Luffy", category: "MELEE", emoji: "👊", image: "images/Monkey_D_Luffy.jpg", title: "Capitan de los Piratas del Sombrero de Paja", anime: "ONE PIECE" },
  { name: "Sanji", category: "MELEE", emoji: "🦵", image: "images/Sanji.jpg", title: "Pierna Negra / Cocinero Pirata", anime: "ONE PIECE" },
  { name: "Garp", category: "MELEE", emoji: "👊", image: "images/Garp.jpg", title: "El Heroe de la Marina / Puño del Dragon", anime: "ONE PIECE" },
  { name: "Yuji Itadori", category: "MELEE", emoji: "👊", image: "images/Yuji_Itadori.jpg", title: "Recipiente de Sukuna / Estudiante de Primero", anime: "Jujutsu Kaisen" },
  { name: "Aoi Todo", category: "MELEE", emoji: "👊", image: "images/Aoi_Todo.jpg", title: "Chaman de Grado Especial / Mejor Amigo de Todo", anime: "JUJUTSU KAISEN" },
  { name: "Maki Zenin", category: "MELEE", emoji: "🗡️", image: "images/Maki_Zenin.jpg", title: "Semibruta del Clan Zenin / Especialista en Armas", anime: "JUJUTSU KAISEN" },
  { name: "Toji Fushiguro", category: "MELEE", emoji: "🔱", image: "images/Toji_Fushiguro.jpg", title: "El Asesino de Chaman / El Sin Energia Maldita", anime: "JUJUTSU KAISEN Season 2" },
  { name: "Naruto Uzumaki", category: "MELEE", emoji: "🦊", image: "images/Naruto_Uzumaki.jpg", title: "Septimo Hokage / Ninja Numero 1 Hiperactivo", anime: "Naruto" },
  { name: "Rock Lee", category: "MELEE", emoji: "👊", image: "images/Rock_Lee.jpg", title: "Especialista en Taijutsu / Ceja Maravillosa", anime: "Naruto" },
  { name: "Might Guy", category: "MELEE", emoji: "👊", image: "images/Might_Guy.jpg", title: "El Ninja Mas Fuerte de Konoha / Maestro de Taijutsu", anime: "Naruto" },
  { name: "Neji Hyuga", category: "MELEE", emoji: "👊", image: "images/Neji_Hyuga.jpg", title: "Genio del Clan Hyuga / Jutsu de Ocho Trigramas", anime: "Naruto" },
  { name: "Choji Akimichi", category: "MELEE", emoji: "👊", image: "images/Choji_Akimichi.jpg", title: "Cabeza de Mariposa / Maestro del Modo Calorias", anime: "Naruto" },
  { name: "Son Goku", category: "MELEE", emoji: "🐉", image: "images/Son_Goku.jpg", title: "Super Saiyan / Guerrero Legendario", anime: "Dragon Ball Z" },
  { name: "Vegeta", category: "MELEE", emoji: "👑", image: "images/Vegeta.jpg", title: "Principe de los Saiyans / El Orgulloso Guerrero", anime: "Dragon Ball Z" },
  { name: "Broly", category: "MELEE", emoji: "💪", image: "images/Broly.jpg", title: "Super Saiyan Legendario / El Saiyan Exiliado", anime: "Dragon Ball Super: Broly" },
  { name: "Jiren", category: "MELEE", emoji: "👊", image: "images/Jiren.jpg", title: "Guerrero del Universo 11 / El Gris", anime: "Dragon Ball Super" },
  { name: "Gohan", category: "MELEE", emoji: "👊", image: "images/Gohan.jpg", title: "El Gran Saiyaman / Hijo de Goku", anime: "Dragon Ball Z" },
  { name: "Piccolo", category: "MELEE", emoji: "👽", image: "images/Piccolo.jpg", title: "Namekusei Demonio / Maestro de Gohan", anime: "Dragon Ball Z" },
  { name: "Gon Freecss", category: "MELEE", emoji: "👊", image: "images/Gon_Freecss.jpg", title: "Aspirante a Cazador / Hijo de Ging", anime: "Hunter x Hunter (2011)" },
  { name: "Killua Zoldyck", category: "MELEE", emoji: "⚡", image: "images/Killua_Zoldyck.jpg", title: "Asesino de la Familia Zoldyck / Usuario de Nen", anime: "Hunter x Hunter (2011)" },
  { name: "Isaac Netero", category: "MELEE", emoji: "☝️", image: "images/Isaac_Netero.jpg", title: "Personaje de Hunter x Hunter (201", anime: "Hunter x Hunter (2011)" },
  { name: "Uvogin", category: "MELEE", emoji: "💪", image: "images/Uvogin.jpg", title: "Personaje de Hunter x Hunter (201", anime: "Hunter x Hunter (2011)" },
  { name: "Phinks", category: "MELEE", emoji: "👊", image: "images/Phinks.jpg", title: "Personaje de Hunter x Hunter (201", anime: "Hunter x Hunter (2011)" },
  { name: "Genos", category: "MELEE", emoji: "🤖", image: "images/Genos.jpg", title: "Demon Cyborg / Estudiante de Saitama", anime: "One-Punch Man" },
  { name: "Saitama", category: "MELEE", emoji: "🥊", image: "images/Saitama.jpg", title: "Caped Baldy / One Punch Man", anime: "One-Punch Man" },
  { name: "Garou", category: "MELEE", emoji: "👊", image: "images/Garou.jpg", title: "El Cazador de Heroes / Human Monster", anime: "One-Punch Man" },
  { name: "Mash Burnedead", category: "MELEE", emoji: "💪", image: "images/Mash_Burnedead.jpg", title: "Sin Magia / Musculos Magicos", anime: "MASHLE: MAGIC AND MUSCLES" },
  { name: "Baki Hanma", category: "MELEE", emoji: "👊", image: "images/Baki_Hanma.jpg", title: "El Campeon / Hijo del Ogro", anime: "BAKI" },
  { name: "Yujiro Hanma", category: "MELEE", emoji: "👊", image: "images/Yujiro_Hanma.jpg", title: "El Ogro / El Mas Fuerte de la Tierra", anime: "BAKI" },
  { name: "Tokita Ohma", category: "MELEE", emoji: "👊", image: "images/Tokita_Ohma.jpg", title: "Personaje de KENGAN ASHURA Part I", anime: "KENGAN ASHURA Part I" },
  { name: "Wakatsuki Takeshi", category: "MELEE", emoji: "👊", image: "images/Wakatsuki_Takeshi.jpg", title: "Personaje de KENGAN ASHURA Part I", anime: "KENGAN ASHURA Part I" },
  { name: "Mori Jin", category: "MELEE", emoji: "👊", image: "images/Mori_Jin.jpg", title: "Personaje de The God of High Scho", anime: "The God of High School" },
  { name: "Han Daewi", category: "MELEE", emoji: "👊", image: "images/Han_Daewi.jpg", title: "Personaje de The God of High Scho", anime: "The God of High School" },
  { name: "Denji", category: "MELEE", emoji: "🪚", image: "images/Denji.jpg", title: "Chainsaw Man / Cazador de Demonios Hibrido", anime: "Chainsaw Man" },
  { name: "Power", category: "MELEE", emoji: "🔨", image: "images/Power.jpg", title: "Demonio de la Sangre / Cazadora de Demonios", anime: "Chainsaw Man" },
  { name: "Shinra Kusakabe", category: "MELEE", emoji: "🔥", image: "images/Shinra_Kusakabe.jpg", title: "Personaje de Fire Force", anime: "Fire Force" },
  { name: "Akaza", category: "MELEE", emoji: "👊", image: "images/Akaza.jpg", title: "Luna Superior Tres / Demonio de Alto Rango", anime: "Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train" },
  { name: "Inosuke Hashibira", category: "MELEE", emoji: "🐗", image: "images/Inosuke_Hashibira.jpg", title: "Cazador de Demonios / Usuario de Respiracion de la Bestia", anime: "Demon Slayer: Kimetsu no Yaiba" },
  { name: "Ban", category: "MELEE", emoji: "👊", image: "images/Ban.jpg", title: "Foxs Sin of Greed / Ladron Inmortal", anime: "The Seven Deadly Sins" },
  { name: "Escanor", category: "MELEE", emoji: "☀️", image: "images/Escanor.jpg", title: "Personaje de The Seven Deadly Sin", anime: "The Seven Deadly Sins: Revival of the Commandments" },
  { name: "All Might", category: "MELEE", emoji: "💪", image: "images/All_Might.jpg", title: "El Simbolo de la Paz / Numero 1 Heroe", anime: "My Hero Academia" },
  { name: "Izuku Midoriya", category: "MELEE", emoji: "👊", image: "images/Izuku_Midoriya.jpg", title: "Deku / Heredero del One For All", anime: "My Hero Academia" },
  { name: "Mirko", category: "MELEE", emoji: "🐰", image: "images/Mirko.jpg", title: "Personaje de My Hero Academia Sea", anime: "My Hero Academia Season 4" },
  { name: "Andy", category: "MELEE", emoji: "👊", image: "images/Andy.jpg", title: "Indestructible / Unluck", anime: "Undead Unluck" },
  { name: "Fuuko Izumo", category: "MELEE", emoji: "👊", image: "images/Fuuko_Izumo.jpg", title: "Desafortunada / Usuario de Unluck", anime: "Undead Unluck" },
  { name: "Eren Yeager", category: "MELEE", emoji: "🦍", image: "images/Eren_Yeager.jpg", title: "Portador del Titan de Ataque / Fundador", anime: "Attack on Titan" },
  { name: "Noi", category: "MELEE", emoji: "💪", image: "images/Noi.jpg", title: "Personaje de Dorohedoro", anime: "Dorohedoro" },
  { name: "Kaiman", category: "MELEE", emoji: "🦎", image: "images/Kaiman.jpg", title: "Personaje de Dorohedoro", anime: "Dorohedoro" },
  { name: "Joseph Joestar", category: "MELEE", emoji: "👊", image: "images/Joseph_Joestar.jpg", title: "Personaje de JoJo's Bizarre Adven", anime: "JoJo's Bizarre Adventure (TV)" },
  { name: "Jonathan Joestar", category: "MELEE", emoji: "👊", image: "images/Jonathan_Joestar.jpg", title: "Personaje de JoJo's Bizarre Adven", anime: "JoJo's Bizarre Adventure (TV)" },
  { name: "Roronoa Zoro", category: "ESPADA", emoji: "⚔️", image: "images/Roronoa_Zoro.jpg", title: "Espadachin Pirata / Cazador de Piratas", anime: "ONE PIECE" },
  { name: "Dracule Mihawk", category: "ESPADA", emoji: "⚔️", image: "images/Dracule_Mihawk.jpg", title: "Ojos de Halcon / Mejor Espadachin del Mundo", anime: "ONE PIECE" },
  { name: "Shanks", category: "ESPADA", emoji: "⚔️", image: "images/Shanks.jpg", title: "El Pelirrojo / Emperador del Mar", anime: "ONE PIECE" },
  { name: "Trafalgar Law", category: "ESPADA", emoji: "⚔️", image: "images/Trafalgar_Law.jpg", title: "Cirujano de la Muerte / Capitan de los Piratas Heart", anime: "ONE PIECE" },
  { name: "Brook", category: "ESPADA", emoji: "⚔️", image: "images/Brook.jpg", title: "Personaje de ONE PIECE", anime: "ONE PIECE" },
  { name: "Kozuki Oden", category: "ESPADA", emoji: "⚔️", image: "images/Kozuki_Oden.jpg", title: "Daimyo de Kuri / Oden Kozuki", anime: "ONE PIECE" },
  { name: "Ichigo Kurosaki", category: "ESPADA", emoji: "⚔️", image: "images/Ichigo_Kurosaki.jpg", title: "Sustituto de Shinigami / Vizard", anime: "Bleach" },
  { name: "Byakuya Kuchiki", category: "ESPADA", emoji: "⚔️", image: "images/Byakuya_Kuchiki.jpg", title: "Capitan del 6to Escuadron / Nobleza de la Sociedad de Almas", anime: "Bleach" },
  { name: "Kenpachi Zaraki", category: "ESPADA", emoji: "⚔️", image: "images/Kenpachi_Zaraki.jpg", title: "Capitan del 11vo Escuadron / El Espadachin Mas Fuerte", anime: "Bleach" },
  { name: "Toshiro Hitsugaya", category: "ESPADA", emoji: "⚔️", image: "images/Toshiro_Hitsugaya.jpg", title: "Capitan del 10mo Escuadron / Hyorinmaru", anime: "Dungeon Meshi PVs" },
  { name: "Genryusai Yamamoto", category: "ESPADA", emoji: "🔥", image: "images/Genryusai_Yamamoto.jpg", title: "Personaje de Rozen Maiden", anime: "Rozen Maiden" },
  { name: "Kisuke Urahara", category: "ESPADA", emoji: "⚔️", image: "images/Kisuke_Urahara.jpg", title: "Ex-Capitan del 12vo Escuadron / Inventor", anime: "Bleach" },
  { name: "Sunraku", category: "ESPADA", emoji: "⚔️", image: "images/Sunraku.jpg", title: "Personaje de Shangri-La Frontier:", anime: "Shangri-La Frontier: Kusoge Hunter, Kamige ni Idoman to su" },
  { name: "Arthur Pencilgon", category: "ESPADA", emoji: "⚔️", image: "images/Arthur_Pencilgon.jpg", title: "Personaje de Shangri-La Frontier:", anime: "Shangri-La Frontier: Kusoge Hunter, Kamige ni Idoman to su" },
  { name: "Tanjiro Kamado", category: "ESPADA", emoji: "🗡️", image: "images/Tanjiro_Kamado.jpg", title: "Cazador de Demonios / Usuario de Respiracion del Sol", anime: "Kimetsu no Yaiba" },
  { name: "Giyu Tomioka", category: "ESPADA", emoji: "🗡️", image: "images/Giyu_Tomioka.jpg", title: "Pilar del Agua / Cazador de Demonios", anime: "Kimetsu no Yaiba" },
  { name: "Kyojuro Rengoku", category: "ESPADA", emoji: "🗡️", image: "images/Kyojuro_Rengoku.jpg", title: "Pilar de las Llamas / Cazador de Demonios", anime: "" },
  { name: "Muichiro Tokito", category: "ESPADA", emoji: "🗡️", image: "images/Muichiro_Tokito.jpg", title: "Personaje de Kimetsu no Yaiba", anime: "Kimetsu no Yaiba" },
  { name: "Zenitsu Agatsuma", category: "ESPADA", emoji: "⚡", image: "images/Zenitsu_Agatsuma.jpg", title: "Cazador de Demonios / Maestro de la Respiracion del Rayo", anime: "Kimetsu no Yaiba" },
  { name: "Yoriichi Tsugikuni", category: "ESPADA", emoji: "🗡️", image: "images/Yoriichi_Tsugikuni.jpg", title: "Personaje de Kimetsu no Yaiba", anime: "Kimetsu no Yaiba" },
  { name: "Sasuke Uchiha", category: "ESPADA", emoji: "⚔️", image: "images/Sasuke_Uchiha.jpg", title: "Sombra del Sexto Hokage / Uchiha del Sharingan", anime: "Naruto" },
  { name: "Killer Bee", category: "ESPADA", emoji: "🐝", image: "images/Killer_Bee.jpg", title: "Personaje de Naruto: Shippuuden", anime: "Naruto: Shippuuden" },
  { name: "Mifune", category: "ESPADA", emoji: "⚔️", image: "images/Mifune.jpg", title: "Personaje de Soul Eater", anime: "Soul Eater" },
  { name: "Asta", category: "ESPADA", emoji: "⚔️", image: "images/Asta.jpg", title: "Usuario Anti-Magia / Sin Magia", anime: "" },
  { name: "Yami Sukehiro", category: "ESPADA", emoji: "⚔️", image: "images/Yami_Sukehiro.jpg", title: "Capitan de los Toros Negros / Magia de Oscuridad", anime: "Black Clover" },
  { name: "Erza Scarlet", category: "ESPADA", emoji: "⚔️", image: "images/Erza_Scarlet.jpg", title: "Reina de las Fadas / Caballero Fairy Tail", anime: "Fairy Tail" },
  { name: "Kirito", category: "ESPADA", emoji: "⚔️", image: "images/Kirito.jpg", title: "El Espadachin Negro / Beta Tester", anime: "" },
  { name: "Asuna Yuuki", category: "ESPADA", emoji: "⚔️", image: "images/Asuna_Yuuki.jpg", title: "Flash / Sub-Lider de los Caballeros de la Sangre", anime: "Sword Art Online" },
  { name: "Alice Zuberg", category: "ESPADA", emoji: "⚔️", image: "images/Alice_Zuberg.jpg", title: "Personaje de Sword Art Online: Al", anime: "Sword Art Online: Alicization" },
  { name: "Guts", category: "ESPADA", emoji: "🗡️", image: "images/Guts.jpg", title: "El Espadachin Negro / Portador de Dragonslayer", anime: "Berserk" },
  { name: "Griffith", category: "ESPADA", emoji: "⚔️", image: "images/Griffith.jpg", title: "Femto / Lider de la Banda del Halcon", anime: "Berserk" },
  { name: "Kenshin Himura", category: "ESPADA", emoji: "⚔️", image: "images/Kenshin_Himura.jpg", title: "Personaje de Rurouni Kenshin: Mei", anime: "Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-hen" },
  { name: "Makoto Shishio", category: "ESPADA", emoji: "⚔️", image: "images/Makoto_Shishio.jpg", title: "Personaje de Rurouni Kenshin: Mei", anime: "Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-hen" },
  { name: "Afro Samurai", category: "ESPADA", emoji: "⚔️", image: "images/Afro_Samurai.jpg", title: "Personaje de Afro Samurai", anime: "Afro Samurai" },
  { name: "Hyakkimaru", category: "ESPADA", emoji: "⚔️", image: "images/Hyakkimaru.jpg", title: "Personaje de Dororo", anime: "Dororo" },
  { name: "Levi Ackerman", category: "ESPADA", emoji: "⚔️", image: "images/Levi_Ackerman.jpg", title: "Capitan / Soldado Mas Fuerte de la Humanidad", anime: "Yuusha no Kuzu" },
  { name: "Mikasa Ackerman", category: "ESPADA", emoji: "⚔️", image: "images/Mikasa_Ackerman.jpg", title: "Los Ackerman / Soldado Elite", anime: "Attack on Titan" },
  { name: "Vergil", category: "ESPADA", emoji: "⚔️", image: "images/Vergil.jpg", title: "Personaje de Devil May Cry 5: Vis", anime: "Devil May Cry 5: Visions of V" },
  { name: "Raiden", category: "ESPADA", emoji: "⚔️", image: "images/Raiden.jpg", title: "Personaje de 86 EIGHTY-SIX", anime: "86 EIGHTY-SIX" },
  { name: "2B", category: "ESPADA", emoji: "⚔️", image: "images/2B.jpg", title: "Personaje de NieR:Automata Ver1.1", anime: "NieR:Automata Ver1.1a" },
  { name: "Saber", category: "ESPADA", emoji: "⚔️", image: "images/Saber.jpg", title: "Rey Arturo / Caballero de la Espada", anime: "Fate/Zero" },
  { name: "Mugen", category: "ESPADA", emoji: "⚔️", image: "images/Mugen.jpg", title: "Personaje de Samurai Champloo", anime: "Samurai Champloo" },
  { name: "Jin", category: "ESPADA", emoji: "⚔️", image: "images/Jin.jpg", title: "Personaje de Solo Leveling", anime: "Solo Leveling" },
  { name: "Hakumen", category: "ESPADA", emoji: "⚔️", image: "images/Hakumen.jpg", title: "Personaje de BlazBlue: Alter Memo", anime: "BlazBlue: Alter Memory" },
  { name: "Sesshomaru", category: "ESPADA", emoji: "⚔️", image: "images/Sesshomaru.jpg", title: "Senor de los Demonios / Hermano de Inuyasha", anime: "InuYasha: The Final Act" },
  { name: "Inuyasha", category: "ESPADA", emoji: "⚔️", image: "images/Inuyasha.jpg", title: "Hanyo / Medio Demonio", anime: "InuYasha" },
  { name: "Kagura Sohma", category: "ESPADA", emoji: "⚔️", image: "images/Kagura_Sohma.jpg", title: "Personaje de ", anime: "" },
  { name: "Charlotte Katakuri", category: "ESPADA", emoji: "⚔️", image: "images/Charlotte_Katakuri.jpg", title: "El Hombre de los 300 Millones / Comandante Dulce", anime: "ONE PIECE" },
  { name: "Ragna the Bloodedge", category: "ESPADA", emoji: "⚔️", image: "images/Ragna_the_Bloodedge.jpg", title: "Personaje de BlazBlue: Alter Memo", anime: "BlazBlue: Alter Memory" },
  { name: "Noctis Lucis Caelum", category: "ESPADA", emoji: "⚔️", image: "images/Noctis_Lucis_Caelum.jpg", title: "Personaje de Brotherhood Final Fa", anime: "Brotherhood Final Fantasy XV" },
  { name: "Yuta Okkotsu", category: "MAGIA", emoji: "✨", image: "images/Yuta_Okkotsu.jpg", title: "Personaje de JUJUTSU KAISEN", anime: "JUJUTSU KAISEN" },
  { name: "Satoru Gojo", category: "MAGIA", emoji: "✨", image: "images/Satoru_Gojo.jpg", title: "El Chaman Mas Fuerte / Profesor de Jujutsu", anime: "JUJUTSU KAISEN" },
  { name: "Megumi Fushiguro", category: "MAGIA", emoji: "✨", image: "images/Megumi_Fushiguro.jpg", title: "Usuario de Tecnicas de Sombras / Estudiante", anime: "JUJUTSU KAISEN" },
  { name: "Ryomen Sukuna", category: "MAGIA", emoji: "✨", image: "images/Ryomen_Sukuna.jpg", title: "Rey de las Maldiciones / La Bestia de 4 Brazos", anime: "Jujutsu Kaisen" },
  { name: "Suguru Geto", category: "MAGIA", emoji: "✨", image: "images/Suguru_Geto.jpg", title: "Personaje de JUJUTSU KAISEN", anime: "JUJUTSU KAISEN" },
  { name: "Mahito", category: "MAGIA", emoji: "✨", image: "images/Mahito.jpg", title: "Personaje de JUJUTSU KAISEN", anime: "JUJUTSU KAISEN" },
  { name: "Choso", category: "MAGIA", emoji: "✨", image: "images/Choso.jpg", title: "Personaje de JUJUTSU KAISEN", anime: "JUJUTSU KAISEN" },
  { name: "Megumin", category: "MAGIA", emoji: "💥", image: "images/Megumin.jpg", title: "Archimaga Explosion / Clan Carmine", anime: "KONOSUBA -God's blessing on this wonderful world!" },
  { name: "Aqua", category: "MAGIA", emoji: "💧", image: "images/Aqua.jpg", title: "Diosa del Agua / Arquiprieta", anime: "KONOSUBA -God's blessing on this wonderful world!" },
  { name: "Frieren", category: "MAGIA", emoji: "✨", image: "images/Frieren.jpg", title: "Maga Elfica / Viajera Eterna", anime: "Frieren: Beyond Journey’s End" },
  { name: "Fern", category: "MAGIA", emoji: "✨", image: "images/Fern.jpg", title: "Personaje de Frieren: Beyond Jour", anime: "Frieren: Beyond Journey’s End" },
  { name: "Portgas D. Ace", category: "MAGIA", emoji: "🔥", image: "images/Portgas_D_Ace.jpg", title: "Puño de Fuego / Comandante de los Piratas de Barbablanca", anime: "ONE PIECE" },
  { name: "Enel", category: "MAGIA", emoji: "⚡", image: "images/Enel.jpg", title: "Dios de Skypiea", anime: "ONE PIECE" },
  { name: "Crocodile", category: "MAGIA", emoji: "🏜️", image: "images/Crocodile.jpg", title: "Mr. 0 / Rey del Desierto", anime: "ONE PIECE" },
  { name: "Aokiji", category: "MAGIA", emoji: "❄️", image: "images/Aokiji.jpg", title: "El Perro Pardo Azul / Almirante de Hielo", anime: "ONE PIECE" },
  { name: "Akainu", category: "MAGIA", emoji: "🔥", image: "images/Akainu.jpg", title: "El Perro Rojo / Almirante de Magma", anime: "ONE PIECE" },
  { name: "Kizaru", category: "MAGIA", emoji: "✨", image: "images/Kizaru.jpg", title: "El Mono Amarillo / Almirante de Luz", anime: "ONE PIECE" },
  { name: "Boa Hancock", category: "MAGIA", emoji: "💕", image: "images/Boa_Hancock.jpg", title: "La Emperatriz Pirata / Princesa Serpiente", anime: "ONE PIECE" },
  { name: "Donquixote Doflamingo", category: "MAGIA", emoji: "🧵", image: "images/Donquixote_Doflamingo.jpg", title: "Joker / Rey de Dressrosa", anime: "ONE PIECE" },
  { name: "Eustass Kid", category: "MAGIA", emoji: "🧲", image: "images/Eustass_Kid.jpg", title: "Capitan Kid / Pirata con Recompensa Alta", anime: "ONE PIECE" },
  { name: "Marco", category: "MAGIA", emoji: "🔥", image: "images/Marco.jpg", title: "El Fénix / Comandante de Barbablanca", anime: "Kidou Butouden G Gundam" },
  { name: "Blackbeard", category: "MAGIA", emoji: "⚫", image: "images/Blackbeard.jpg", title: "Marshall D. Teach / Emperador de las Tinieblas", anime: "Wu Liuqi: Xuanwu Guo Pian" },
  { name: "Perona", category: "MAGIA", emoji: "👻", image: "images/Perona.jpg", title: "Personaje de One Piece", anime: "One Piece" },
  { name: "Bartolomeo", category: "MAGIA", emoji: "🛡️", image: "images/Bartolomeo.jpg", title: "Personaje de One Piece", anime: "One Piece" },
  { name: "Rimuru Tempest", category: "MAGIA", emoji: "💧", image: "images/Rimuru_Tempest.jpg", title: "Monarca Demonio / Slime Reencarnado", anime: "That Time I Got Reincarnated as a Slime" },
  { name: "Milim Nava", category: "MAGIA", emoji: "✨", image: "images/Milim_Nava.jpg", title: "Uno de los Ocho Demonios / Dragona Destructora", anime: "Tensei shitara Slime Datta Ken" },
  { name: "Diablo", category: "MAGIA", emoji: "✨", image: "images/Diablo.jpg", title: "Personaje de Shinjiteita Nakama-t", anime: "Shinjiteita Nakama-tachi ni Dungeon Okuchi de Korosarekaketa ga Gift \"Mugen Gacha\" de Level 9999 no Nakama-tachi wo Te ni Irete Moto Party Member to Sekai ni Fukushuu & \"Zamaa!\" Shimasu!" },
  { name: "Lucy Heartfilia", category: "MAGIA", emoji: "✨", image: "images/Lucy_Heartfilia.jpg", title: "Maga de Espiritus Celestiales", anime: "Fairy Tail" },
  { name: "Zeref", category: "MAGIA", emoji: "✨", image: "images/Zeref.jpg", title: "Personaje de Fairy Tail", anime: "Fairy Tail" },
  { name: "Julius Novachrono", category: "MAGIA", emoji: "⏰", image: "images/Julius_Novachrono.jpg", title: "Personaje de Black Clover", anime: "Black Clover" },
  { name: "Yuno", category: "MAGIA", emoji: "✨", image: "images/Yuno.jpg", title: "Usuario de Magia de Viento / El Cisne de Cuatro Hojas", anime: "Tensei shitara Dragon no Tamago datta" },
  { name: "Noelle Silva", category: "MAGIA", emoji: "🌊", image: "images/Noelle_Silva.jpg", title: "Usuario de Magia de Agua / Princesa de la Casa Silva", anime: "Black Clover" },
  { name: "Shigeo Kageyama", category: "MAGIA", emoji: "✨", image: "images/Shigeo_Kageyama.jpg", title: "Personaje de Mob Psycho 100", anime: "Mob Psycho 100" },
  { name: "Tatsumaki", category: "MAGIA", emoji: "🌪️", image: "images/Tatsumaki.jpg", title: "Personaje de Lupin III: Part II", anime: "Lupin III: Part II" },
  { name: "Fubuki", category: "MAGIA", emoji: "❄️", image: "images/Fubuki.jpg", title: "Personaje de Kyokou Suiri Season ", anime: "Kyokou Suiri Season 2" },
  { name: "Madoka Kaname", category: "MAGIA", emoji: "✨", image: "images/Madoka_Kaname.jpg", title: "Dios de las Chicas Magicas", anime: "Mahou Shoujo Madoka★Magica" },
  { name: "Homura Akemi", category: "MAGIA", emoji: "⏰", image: "images/Homura_Akemi.jpg", title: "Chica Magica del Tiempo", anime: "Puella Magi Madoka Magica" },
  { name: "Mami Tomoe", category: "MAGIA", emoji: "🔫", image: "images/Mami_Tomoe.jpg", title: "Personaje de Mahou Shoujo Madoka★", anime: "Mahou Shoujo Madoka★Magica" },
  { name: "Ainz Ooal Gown", category: "MAGIA", emoji: "💀", image: "images/Ainz_Ooal_Gown.jpg", title: "Rey Hechicero / Lider de Nazarick", anime: "" },
  { name: "Emilia", category: "MAGIA", emoji: "❄️", image: "images/Emilia.jpg", title: "Semibruta de Hielo / Candidata a Reina", anime: "" },
  { name: "Beatrice", category: "MAGIA", emoji: "✨", image: "images/Beatrice.jpg", title: "Personaje de ", anime: "" },
  { name: "Roxy Migurdia", category: "MAGIA", emoji: "✨", image: "images/Roxy_Migurdia.jpg", title: "Maga Migurd / Maestra de Rudeus", anime: "Mushoku Tensei: Isekai Ittara Honki Dasu" },
  { name: "Rudeus Greyrat", category: "MAGIA", emoji: "✨", image: "images/Rudeus_Greyrat.jpg", title: "Mago Renaciente / Ojos Demoniacos", anime: "Mushoku Tensei: Isekai Ittara Honki Dasu" },
  { name: "Anos Voldigoad", category: "MAGIA", emoji: "✨", image: "images/Anos_Voldigoad.jpg", title: "Personaje de The Misfit of Demon ", anime: "The Misfit of Demon King Academy: History’s Strongest Demon King Reincarnates and Goes to School with His Descendants" },
  { name: "Howl", category: "MAGIA", emoji: "✨", image: "images/Howl.jpg", title: "Personaje de Howl‘s Moving Castle", anime: "Howl‘s Moving Castle" },
  { name: "Sailor Moon", category: "MAGIA", emoji: "🌙", image: "images/Sailor_Moon.jpg", title: "Soldado de la Justicia / Usagi Tsukino", anime: "Sailor Moon" },
  { name: "Sailor Mars", category: "MAGIA", emoji: "🔥", image: "images/Sailor_Mars.jpg", title: "Personaje de Sailor Moon", anime: "Sailor Moon" },
  { name: "Sailor Mercury", category: "MAGIA", emoji: "💧", image: "images/Sailor_Mercury.jpg", title: "Personaje de Sailor Moon", anime: "Sailor Moon" },
  { name: "Sailor Jupiter", category: "MAGIA", emoji: "⚡", image: "images/Sailor_Jupiter.jpg", title: "Personaje de Sailor Moon", anime: "Sailor Moon" },
  { name: "Gilgamesh", category: "MAGIA", emoji: "✨", image: "images/Gilgamesh.jpg", title: "Rey de los Heroes / Puertas de Babilonia", anime: "Fate/Zero" },
];

const categories = ['MELEE', 'ESPADA', 'MAGIA'];
