// Lista curada de personajes desde resultados v1.xlsx
const candidates = [
  // MELEE - 38 personajes
  { name: "Monkey D. Luffy", category: "MELEE", emoji: "👊", anime: "ONE PIECE" },
  { name: "Sanji", category: "MELEE", emoji: "🦵", anime: "ONE PIECE" },
  { name: "Yuji Itadori", category: "MELEE", emoji: "👊", anime: "Jujutsu Kaisen" },
  { name: "Aoi Todo", category: "MELEE", emoji: "👊", anime: "JUJUTSU KAISEN" },
  { name: "Maki Zenin", category: "MELEE", emoji: "🗡️", anime: "JUJUTSU KAISEN" },
  { name: "Toji Fushiguro", category: "MELEE", emoji: "🔱", anime: "JUJUTSU KAISEN Season 2" },
  { name: "Naoya Zenin", category: "MELEE", emoji: "👊", anime: "JUJUTSU KAISEN" },
  { name: "Naruto Uzumaki", category: "MELEE", emoji: "🦊", anime: "Naruto" },
  { name: "Rock Lee", category: "MELEE", emoji: "👊", anime: "Naruto" },
  { name: "Son Goku", category: "MELEE", emoji: "🐉", anime: "Dragon Ball Z" },
  { name: "Vegeta", category: "MELEE", emoji: "👑", anime: "Dragon Ball Z" },
  { name: "Broly", category: "MELEE", emoji: "💪", anime: "Dragon Ball Super: Broly" },
  { name: "Gohan", category: "MELEE", emoji: "👊", anime: "Dragon Ball Z" },
  { name: "Piccolo", category: "MELEE", emoji: "👽", anime: "Dragon Ball Z" },
  { name: "Gon Freecss", category: "MELEE", emoji: "👊", anime: "Hunter x Hunter (2011)" },
  { name: "Killua Zoldyck", category: "MELEE", emoji: "⚡", anime: "Hunter x Hunter (2011)" },
  { name: "Genos", category: "MELEE", emoji: "🤖", anime: "One-Punch Man" },
  { name: "Saitama", category: "MELEE", emoji: "🥊", anime: "One-Punch Man" },
  { name: "Garou", category: "MELEE", emoji: "👊", anime: "One-Punch Man" },
  { name: "Baki Hanma", category: "MELEE", emoji: "👊", anime: "BAKI" },
  { name: "Yujiro hanma", category: "MELEE", emoji: "👊", anime: "BAKI" },
  { name: "Mori Jin", category: "MELEE", emoji: "👊", anime: "The God of High School" },
  { name: "Han Daewi", category: "MELEE", emoji: "👊", anime: "The God of High School" },
  { name: "Denji", category: "MELEE", emoji: "🪚", anime: "Chainsaw Man" },
  { name: "Power", category: "MELEE", emoji: "🔨", anime: "Chainsaw Man" },
  { name: "Shinra Kusakabe", category: "MELEE", emoji: "🔥", anime: "Fire Force" },
  { name: "Akaza", category: "MELEE", emoji: "👊", anime: "Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train" },
  { name: "Ban", category: "MELEE", emoji: "👊", anime: "The Seven Deadly Sins" },
  { name: "All Might", category: "MELEE", emoji: "💪", anime: "My Hero Academia" },
  { name: "Izuku Midoriya", category: "MELEE", emoji: "👊", anime: "My Hero Academia" },
  { name: "Mirko", category: "MELEE", emoji: "🐰", anime: "My Hero Academia Season 4" },
  { name: "Eren Yeager", category: "MELEE", emoji: "🦍", anime: "Attack on Titan" },
  { name: "Joseph Joestar", category: "MELEE", emoji: "👊", anime: "JoJo's Bizarre Adventure (TV)" },
  { name: "Jonathan Joestar", category: "MELEE", emoji: "👊", anime: "JoJo's Bizarre Adventure (TV)" },
  { name: "DIO", category: "MELEE", emoji: "👊", anime: "JoJo's Bizarre Adventure (TV)" },
  { name: "Yujiro hanma", category: "MELEE", emoji: "👊", anime: "BAKI" },
  { name: "Benimaru Shinmon", category: "MELEE", emoji: "🔥", anime: "Fire Force" },
  { name: "Kaneki", category: "MELEE", emoji: "👊", anime: "Tokyo Ghoul" },
  { name: "Eto", category: "MELEE", emoji: "👊", anime: "Tokyo Ghoul" },

  // ESPADA - 45 personajes
  { name: "Roronoa Zoro", category: "ESPADA", emoji: "⚔️", anime: "ONE PIECE" },
  { name: "Dracule Mihawk", category: "ESPADA", emoji: "⚔️", anime: "OnE PIECE" },
  { name: "Shanks", category: "ESPADA", emoji: "⚔️", anime: "ONE PIECE" },
  { name: "Trafalgar Law", category: "ESPADA", emoji: "⚔️", anime: "ONE PIECE" },
  { name: "Ichigo", category: "ESPADA", emoji: "⚔️", anime: "BLEACH" },
  { name: "Biakuya Kuchiki", category: "ESPADA", emoji: "⚔️", anime: "BLEACH" },
  { name: "Kenpachi Zaraki", category: "ESPADA", emoji: "⚔️", anime: "BLEACH" },
  { name: "Genryusai Yamamoto", category: "ESPADA", emoji: "⚔️", anime: "BLEACH" },
  { name: "Kisuke Urahara", category: "ESPADA", emoji: "⚔️", anime: "BLEACH" },
  { name: "Sunraku", category: "ESPADA", emoji: "⚔️", anime: "SHANGRI-LA FRONTIER" },
  { name: "Arthur Pencilgon", category: "ESPADA", emoji: "⚔️", anime: "SHANGRI-LA FRONTIER" },
  { name: "Tanjiro Kamado", category: "ESPADA", emoji: "⚔️", anime: "KIMETSU NO YAIBA" },
  { name: "Giyu Tomioka", category: "ESPADA", emoji: "⚔️", anime: "KIMETSU NO YAIBA" },
  { name: "Kyojuro Rengoku", category: "ESPADA", emoji: "⚔️", anime: "KIMETSU NO YAIBA" },
  { name: "Muichiro Tokito", category: "ESPADA", emoji: "⚔️", anime: "KIMETSU NO YAIBA" },
  { name: "Zenitsu Agatsuma", category: "ESPADA", emoji: "⚔️", anime: "KIMETSU NO YAIBA" },
  { name: "Yoriichi Tsugikuni", category: "ESPADA", emoji: "⚔️", anime: "KIMETSU NO YAIBA" },
  { name: "Sasuke Uchiha", category: "ESPADA", emoji: "⚔️", anime: "NARUTO" },
  { name: "Mifune", category: "ESPADA", emoji: "⚔️", anime: "SOUL EATER" },
  { name: "Asta", category: "ESPADA", emoji: "⚔️", anime: "BLACK CLOVER" },
  { name: "Erza Scarlet", category: "ESPADA", emoji: "⚔️", anime: "FAIRY TAIL" },
  { name: "Kirito", category: "ESPADA", emoji: "⚔️", anime: "SAO" },
  { name: "Asuna Yuuki", category: "ESPADA", emoji: "⚔️", anime: "SAO" },
  { name: "Guts", category: "ESPADA", emoji: "⚔️", anime: "BERSERK" },
  { name: "Griffith", category: "ESPADA", emoji: "⚔️", anime: "BERSERK" },
  { name: "Kenshin Himura", category: "ESPADA", emoji: "⚔️", anime: "SAMURAI X" },
  { name: "Hyakkimaru", category: "ESPADA", emoji: "⚔️", anime: "DORORO" },
  { name: "Levi Ackerman", category: "ESPADA", emoji: "⚔️", anime: "ATTACK ON TITAN" },
  { name: "Mikasa Ackerman", category: "ESPADA", emoji: "⚔️", anime: "ATTACK ON TITAN" },
  { name: "Vergil", category: "ESPADA", emoji: "⚔️", anime: "DEVIL MAY CRY" },
  { name: "Raiden", category: "ESPADA", emoji: "⚔️", anime: "METAL GEAR RISING" },
  { name: "B2", category: "ESPADA", emoji: "⚔️", anime: "NIER: AUTOMATA" },
  { name: "Saber", category: "ESPADA", emoji: "⚔️", anime: "FATE" },
  { name: "Mugen", category: "ESPADA", emoji: "⚔️", anime: "SAMURAI CHAMPLOO" },
  { name: "Jinwoo Sung", category: "ESPADA", emoji: "⚔️", anime: "SOLO LEVELING" },
  { name: "Hakumen", category: "ESPADA", emoji: "⚔️", anime: "BLAZBLUE" },
  { name: "Sesshomaru", category: "ESPADA", emoji: "⚔️", anime: "INUYASHA" },
  { name: "inuyasha", category: "ESPADA", emoji: "⚔️", anime: "INUYASHA" },
  { name: "Ragna the Bloodedge", category: "ESPADA", emoji: "⚔️", anime: "BLAZBLUE" },
  { name: "Noctis Lucis Caelum", category: "ESPADA", emoji: "⚔️", anime: "FINAL FANTASY XV" },
  { name: "Dante", category: "ESPADA", emoji: "⚔️", anime: "DEVIL MAY CRY" },
  { name: "Rimuru Tempest", category: "ESPADA", emoji: "⚔️", anime: "That Time I Got Reincarnated as a Slime" },
  { name: "Inosuke Hashibira", category: "ESPADA", emoji: "⚔️", anime: "Demon Slayer: Kimetsu no Yaiba" },
  { name: "Escanor", category: "ESPADA", emoji: "⚔️", anime: "The Seven Deadly Sins: Revival of the Commandments" },
  { name: "Sho Kusakabe", category: "ESPADA", emoji: "⚔️", anime: "Fire Force" },

  // MAGIA - 38 personajes
  { name: "Yuta Okkotsu", category: "MAGIA", emoji: "✨", anime: "JUJUTSU KAISEN" },
  { name: "Satoru Gojo", category: "MAGIA", emoji: "✨", anime: "JUJUTSU KAISEN" },
  { name: "Megumi Fushiguro", category: "MAGIA", emoji: "✨", anime: "JUJUTSU KAISEN" },
  { name: "Ryomen Sukuna", category: "MAGIA", emoji: "✨", anime: "Jujutsu Kaisen" },
  { name: "Suguru Geto (kenjaku?)", category: "MAGIA", emoji: "✨", anime: "JUJUTSU KAISEN" },
  { name: "Mahito", category: "MAGIA", emoji: "✨", anime: "JUJUTSU KAISEN" },
  { name: "Choso", category: "MAGIA", emoji: "✨", anime: "JUJUTSU KAISEN" },
  { name: "Megumin", category: "MAGIA", emoji: "💥", anime: "KONOSUBA -God's blessing on this wonderful world!" },
  { name: "Frieren", category: "MAGIA", emoji: "✨", anime: "Frieren: Beyond Journey's End" },
  { name: "Fern", category: "MAGIA", emoji: "✨", anime: "Frieren: Beyond Journey's End" },
  { name: "Portgas D. Ace", category: "MAGIA", emoji: "🔥", anime: "ONE PIECE" },
  { name: "Aokiji", category: "MAGIA", emoji: "❄️", anime: "ONE PIECE" },
  { name: "Akainu", category: "MAGIA", emoji: "🔥", anime: "ONE PIECE" },
  { name: "Kizaru", category: "MAGIA", emoji: "✨", anime: "ONE PIECE" },
  { name: "Boa Hancock", category: "MAGIA", emoji: "💕", anime: "ONE PIECE" },
  { name: "Eustass Kid", category: "MAGIA", emoji: "🧲", anime: "ONE PIECE" },
  { name: "Blackbeard", category: "MAGIA", emoji: "🌑", anime: "ONE PIECE" },
  { name: "Perona", category: "MAGIA", emoji: "👻", anime: "One Piece" },
  { name: "Charlotte Katakuri", category: "MAGIA", emoji: "🍩", anime: "ONE PIECE" },
  { name: "Milim Nava", category: "MAGIA", emoji: "✨", anime: "Tensei shitara Slime Datta Ken" },
  { name: "Diablo", category: "MAGIA", emoji: "✨", anime: "That Time I Got Reincarnated as a Slime" },
  { name: "Lucy Heartfilia", category: "MAGIA", emoji: "✨", anime: "Fairy Tail" },
  { name: "Zeref", category: "MAGIA", emoji: "🖤", anime: "Fairy Tail" },
  { name: "Noelle Silva", category: "MAGIA", emoji: "✨", anime: "Black Clover" },
  { name: "Tatsumaki", category: "MAGIA", emoji: "🌪️", anime: "one punch man" },
  { name: "Madoka Kaname", category: "MAGIA", emoji: "✨", anime: "Mahou Shoujo Madoka★Magica" },
  { name: "Homura Akemi", category: "MAGIA", emoji: "✨", anime: "Mahou Shoujo Madoka★Magica" },
  { name: "Mami Tomoe", category: "MAGIA", emoji: "✨", anime: "Mahou Shoujo Madoka★Magica" },
  { name: "Ainz Ooal Gown", category: "MAGIA", emoji: "💀", anime: "Overlord" },
  { name: "Emilia", category: "MAGIA", emoji: "✨", anime: "Re zero" },
  { name: "Beatrice", category: "MAGIA", emoji: "✨", anime: "Re zero" },
  { name: "Roxy Migurdia", category: "MAGIA", emoji: "✨", anime: "Mushoku Tensei: Isekai Ittara Honki Dasu" },
  { name: "Rudeus Greyrat", category: "MAGIA", emoji: "✨", anime: "Mushoku Tensei: Isekai Ittara Honki Dasu" },
  { name: "Anos Voldigoad", category: "MAGIA", emoji: "✨", anime: "The Misfit of Demon King Academy" },
  { name: "Howl", category: "MAGIA", emoji: "✨", anime: "Howl's Moving Castle" },
  { name: "Sailor Moon", category: "MAGIA", emoji: "🌙", anime: "Sailor Moon" },
  { name: "Sailor Mars", category: "MAGIA", emoji: "🔥", anime: "Sailor Moon" },
  { name: "Sailor Mercury", category: "MAGIA", emoji: "💧", anime: "Sailor Moon" },
  { name: "Gilgamesh", category: "MAGIA", emoji: "✨", anime: "Fate/Zero" }
];

const categories = ['MELEE', 'ESPADA', 'MAGIA'];

// Exportar para Node.js (si es necesario)
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { candidates, categories };
}
