// Lista curada de personajes desde resultados v1.xlsx con imágenes y descripciones
const candidates = [
  // MELEE - 38 personajes
  { name: "Monkey D. Luffy", category: "MELEE", emoji: "👊", anime: "ONE PIECE", image: "https://s4.anilist.co/file/anilistcdn/character/large/b40-MNypXsxSRb1R.png", title: "Capitán de los Piratas del Sombrero de Paja" },
  { name: "Sanji", category: "MELEE", emoji: "🦵", anime: "ONE PIECE", image: "https://s4.anilist.co/file/anilistcdn/character/large/b305-6lisPmHtCnLT.png", title: "Pierna Negra / Cocinero Pirata" },
  { name: "Yuji Itadori", category: "MELEE", emoji: "👊", anime: "Jujutsu Kaisen", image: "https://s4.anilist.co/file/anilistcdn/character/large/b131407-5bBIAnku8xlm.png", title: "Recipiente de Sukuna / Hechicero de Jujutsu" },
  { name: "Aoi Todo", category: "MELEE", emoji: "👊", anime: "JUJUTSU KAISEN", image: "https://s4.anilist.co/file/anilistcdn/character/large/b149173-8z4MTTnm8Iln.png", title: "Hechicero de Grado Especial" },
  { name: "Maki Zenin", category: "MELEE", emoji: "🗡️", anime: "JUJUTSU KAISEN", image: "https://s4.anilist.co/file/anilistcdn/character/large/b149179-ojf3wW4s7JhH.png", title: "Semibruta del Clan Zenin" },
  { name: "Toji Fushiguro", category: "MELEE", emoji: "🔱", anime: "JUJUTSU KAISEN Season 2", image: "https://s4.anilist.co/file/anilistcdn/character/large/b182477-rc0dDWNNIg4s.png", title: "El Asesino de Hechiceros / Sin Energía Maldita" },
  { name: "Naoya Zenin", category: "MELEE", emoji: "👊", anime: "JUJUTSU KAISEN", image: "https://s4.anilist.co/file/anilistcdn/character/large/b182479-q2m7jfu7G1hF.png", title: "Hechicero del Clan Zenin" },
  { name: "Naruto Uzumaki", category: "MELEE", emoji: "🦊", anime: "Naruto", image: "https://s4.anilist.co/file/anilistcdn/character/large/b17-E7dijqXyHnmH.png", title: "Séptimo Hokage / Ninja de la Hoja" },
  { name: "Rock Lee", category: "MELEE", emoji: "👊", anime: "Naruto", image: "https://s4.anilist.co/file/anilistcdn/character/large/b306-L1SNOdzJ5g9d.png", title: "Especialista en Taijutsu / Ceja Maravillosa" },
  { name: "Son Goku", category: "MELEE", emoji: "🐉", anime: "Dragon Ball Z", image: "https://s4.anilist.co/file/anilistcdn/character/large/b246-BevvmKz4i6fi.png", title: "Super Saiyan / Guerrero Legendario" },
  { name: "Vegeta", category: "MELEE", emoji: "👑", anime: "Dragon Ball Z", image: "https://s4.anilist.co/file/anilistcdn/character/large/b243-p1W9VvR4v9Qj.png", title: "Príncipe de los Saiyans" },
  { name: "Broly", category: "MELEE", emoji: "💪", anime: "Dragon Ball Super: Broly", image: "https://s4.anilist.co/file/anilistcdn/character/large/g106577-T0Nz9P7j8RNF.png", title: "Super Saiyan Legendario" },
  { name: "Gohan", category: "MELEE", emoji: "👊", anime: "Dragon Ball Z", image: "https://s4.anilist.co/file/anilistcdn/character/large/b246-BevvmKz4i6fi.png", title: "El Gran Saiyaman / Hijo de Goku" },
  { name: "Piccolo", category: "MELEE", emoji: "👽", anime: "Dragon Ball Z", image: "https://s4.anilist.co/file/anilistcdn/character/large/b244-uY2gVfw7G64O.png", title: "Namekusei / Maestro de Gohan" },
  { name: "Gon Freecss", category: "MELEE", emoji: "👊", anime: "Hunter x Hunter (2011)", image: "https://s4.anilist.co/file/anilistcdn/character/large/b30-1klzM5HFLr1T.png", title: "Aspirante a Cazador / Hijo de Ging" },
  { name: "Killua Zoldyck", category: "MELEE", emoji: "⚡", anime: "Hunter x Hunter (2011)", image: "https://s4.anilist.co/file/anilistcdn/character/large/b31-kxCJ4TDg7Pso.png", title: "Asesino de la Familia Zoldyck" },
  { name: "Genos", category: "MELEE", emoji: "🤖", anime: "One-Punch Man", image: "https://s4.anilist.co/file/anilistcdn/character/large/b73973-LX7J8S2C6y3l.png", title: "Demonio Cyborg / Discípulo de Saitama" },
  { name: "Saitama", category: "MELEE", emoji: "🥊", anime: "One-Punch Man", image: "https://s4.anilist.co/file/anilistcdn/character/large/b73975-OjBqf9U5ZxvH.png", title: "One Punch Man / Cabezón Calvo" },
  { name: "Garou", category: "MELEE", emoji: "👊", anime: "One-Punch Man", image: "https://s4.anilist.co/file/anilistcdn/character/large/b111837-8Tac3m1nAhfi.png", title: "El Cazador de Héroes / Monstruo Humano" },
  { name: "Baki Hanma", category: "MELEE", emoji: "👊", anime: "BAKI", image: "https://s4.anilist.co/file/anilistcdn/character/large/b12091-vY8R2s9k0Mh1.png", title: "Campeón / Hijo del Ogro" },
  { name: "Yujiro hanma", category: "MELEE", emoji: "👊", anime: "BAKI", image: "https://s4.anilist.co/file/anilistcdn/character/large/b6699-GnA0vzNcwvZ4.png", title: "El Ogro / El Más Fuerte de la Tierra" },
  { name: "Mori Jin", category: "MELEE", emoji: "👊", anime: "The God of High School", image: "https://s4.anilist.co/file/anilistcdn/character/large/b127149-t4ZoIS0u1cK6.png", title: "Estudiante de Taekwondo / Dios Mono" },
  { name: "Han Daewi", category: "MELEE", emoji: "👊", anime: "The God of High School", image: "https://s4.anilist.co/file/anilistcdn/character/large/b127150-T4n6r2jUo6z1.png", title: "Estudiante de Boxeo / Rey Dragón" },
  { name: "Denji", category: "MELEE", emoji: "🪚", anime: "Chainsaw Man", image: "https://s4.anilist.co/file/anilistcdn/character/large/b138167-u7lwNOt0PFlr.png", title: "Chainsaw Man / Cazador de Demonios Híbrido" },
  { name: "Power", category: "MELEE", emoji: "🔨", anime: "Chainsaw Man", image: "https://s4.anilist.co/file/anilistcdn/character/large/b138169-Zb2X0j5lD7Y1.png", title: "Demonio de la Sangre / Cazadora de Demonios" },
  { name: "Shinra Kusakabe", category: "MELEE", emoji: "🔥", anime: "Fire Force", image: "https://s4.anilist.co/file/anilistcdn/character/large/b105964-8RqC94fG6k2m.png", title: "Pies Infernales / Bombero de la Compañía 8" },
  { name: "Akaza", category: "MELEE", emoji: "👊", anime: "Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train", image: "https://s4.anilist.co/file/anilistcdn/character/large/b129054-3yR0Q3rVnX6E.png", title: "Luna Superior Tres / Demonio de Alto Rango" },
  { name: "Ban", category: "MELEE", emoji: "👊", anime: "The Seven Deadly Sins", image: "https://s4.anilist.co/file/anilistcdn/character/large/b58453-VzZn7mXkI4p6.png", title: "Fox's Sin of Greed / Ladrón Inmortal" },
  { name: "All Might", category: "MELEE", emoji: "💪", anime: "My Hero Academia", image: "https://s4.anilist.co/file/anilistcdn/character/large/b65494-PFwRwEb7xPFD.png", title: "El Símbolo de la Paz / Héroe No. 1" },
  { name: "Izuku Midoriya", category: "MELEE", emoji: "👊", anime: "My Hero Academia", image: "https://s4.anilist.co/file/anilistcdn/character/large/b65489-1p9Xj5v9S6qN.png", title: "Deku / Heredero del One For All" },
  { name: "Mirko", category: "MELEE", emoji: "🐰", anime: "My Hero Academia Season 4", image: "https://s4.anilist.co/file/anilistcdn/character/large/b155679-6uR5v0k5f5h3.png", title: "Rabbit Hero: Mirko / Héroe Profesional No. 5" },
  { name: "Eren Yeager", category: "MELEE", emoji: "🦍", anime: "Attack on Titan", image: "https://s4.anilist.co/file/anilistcdn/character/large/b45627-9q8pF4s5q2tD.png", title: "Portador del Titán de Ataque / Fundador" },
  { name: "Joseph Joestar", category: "MELEE", emoji: "👊", anime: "JoJo's Bizarre Adventure (TV)", image: "https://s4.anilist.co/file/anilistcdn/character/large/b4356-0g6R0R6f7d7N.png", title: "Usuario de Hamon / Héroe de la Segunda Parte" },
  { name: "Jonathan Joestar", category: "MELEE", emoji: "👊", anime: "JoJo's Bizarre Adventure (TV)", image: "https://s4.anilist.co/file/anilistcdn/character/large/b4355-4z4V0d9t6h7N.png", title: "Caballero Gentil / Primer JoJo" },
  { name: "DIO", category: "MELEE", emoji: "👊", anime: "JoJo's Bizarre Adventure (TV)", image: "https://s4.anilist.co/file/anilistcdn/character/large/b4358-s4S7R7t9P7hN.png", title: "El Vampiro Inmortal / Usuario de The World" },
  { name: "Yujiro hanma", category: "MELEE", emoji: "👊", anime: "BAKI", image: "https://s4.anilist.co/file/anilistcdn/character/large/b6699-GnA0vzNcwvZ4.png", title: "El Ogro / El Más Fuerte de la Tierra" },
  { name: "Benimaru Shinmon", category: "MELEE", emoji: "🔥", anime: "Fire Force", image: "https://s4.anilist.co/file/anilistcdn/character/large/b105967-Xx5x0P9n0v1y.png", title: "Capitán de la Compañía 7 / Pilar Carmesí" },
  { name: "Kaneki", category: "MELEE", emoji: "👊", anime: "Tokyo Ghoul", image: "https://s4.anilist.co/file/anilistcdn/character/large/b65301-T0x7P7x0h1yN.png", title: "Ghoul de Ojo Negro / Centopeia" },
  { name: "Eto", category: "MELEE", emoji: "👊", anime: "Tokyo Ghoul", image: "https://s4.anilist.co/file/anilistcdn/character/large/b65303-3yR0Q3rVnX6E.png", title: "Búho de Un Solo Ojo / Autor de Sen Takatsuki" },

  // ESPADA - 45 personajes
  { name: "Roronoa Zoro", category: "ESPADA", emoji: "⚔️", anime: "ONE PIECE", image: "https://s4.anilist.co/file/anilistcdn/character/large/b304-1r5qor5ZBE1X.png", title: "Espadachín Pirata / Cazador de Piratas" },
  { name: "Dracule Mihawk", category: "ESPADA", emoji: "⚔️", anime: "OnE PIECE", image: "https://s4.anilist.co/file/anilistcdn/character/large/b64-l4Q0Q8v8y8h6.png", title: "Ojos de Halcón / Mejor Espadachín del Mundo" },
  { name: "Shanks", category: "ESPADA", emoji: "⚔️", anime: "ONE PIECE", image: "https://s4.anilist.co/file/anilistcdn/character/large/b39-5t8M6B8y8h6.png", title: "El Pelirrojo / Emperador del Mar" },
  { name: "Trafalgar Law", category: "ESPADA", emoji: "⚔️", anime: "ONE PIECE", image: "https://s4.anilist.co/file/anilistcdn/character/large/b17620-1r5qor5ZBE1X.png", title: "Cirujano de la Muerte / Usuario de la Ope Ope no Mi" },
  { name: "Ichigo", category: "ESPADA", emoji: "⚔️", anime: "BLEACH", image: "https://s4.anilist.co/file/anilistcdn/character/large/b5-3yR0Q3rVnX6E.png", title: "Substitute Shinigami / Vizard" },
  { name: "Biakuya Kuchiki", category: "ESPADA", emoji: "⚔️", anime: "BLEACH", image: "https://s4.anilist.co/file/anilistcdn/character/large/b14-0g6R0R6f7d7N.png", title: "Capitán de la 6ª División / Noble de la Sociedad de Almas" },
  { name: "Kenpachi Zaraki", category: "ESPADA", emoji: "⚔️", anime: "BLEACH", image: "https://s4.anilist.co/file/anilistcdn/character/large/b33-8RqC94fG6k2m.png", title: "Capitán de la 11ª División / El Espadachín Más Fuerte" },
  { name: "Genryusai Yamamoto", category: "ESPADA", emoji: "⚔️", anime: "BLEACH", image: "https://s4.anilist.co/file/anilistcdn/character/large/b26-8z4MTTnm8Iln.png", title: "Capitán Comandante / Fundador del Gotei 13" },
  { name: "Kisuke Urahara", category: "ESPADA", emoji: "⚔️", anime: "BLEACH", image: "https://s4.anilist.co/file/anilistcdn/character/large/b32-5bBIAnku8xlm.png", title: "Ex-Capitán de la 12ª División / Inventor" },
  { name: "Sunraku", category: "ESPADA", emoji: "⚔️", anime: "SHANGRI-LA FRONTIER", image: "https://s4.anilist.co/file/anilistcdn/character/large/b206673-6uR5v0k5f5h3.png", title: "Jugador de Shangri-La Frontier / Samurai" },
  { name: "Arthur Pencilgon", category: "ESPADA", emoji: "⚔️", anime: "SHANGRI-LA FRONTIER", image: "https://s4.anilist.co/file/anilistcdn/character/large/b206677-8RqC94fG6k2m.png", title: "Jugador de SLF / Líder de la Fábrica Ashura" },
  { name: "Tanjiro Kamado", category: "ESPADA", emoji: "⚔️", anime: "KIMETSU NO YAIBA", image: "https://s4.anilist.co/file/anilistcdn/character/large/b127533-6uR5v0k5f5h3.png", title: "Cazador de Demonios / Respiración del Sol" },
  { name: "Giyu Tomioka", category: "ESPADA", emoji: "⚔️", anime: "KIMETSU NO YAIBA", image: "https://s4.anilist.co/file/anilistcdn/character/large/b127535-T0x7P7x0h1yN.png", title: "Pilar del Agua / Cazador de Demonios" },
  { name: "Kyojuro Rengoku", category: "ESPADA", emoji: "⚔️", anime: "KIMETSU NO YAIBA", image: "https://s4.anilist.co/file/anilistcdn/character/large/b129052-Xx5x0P9n0v1y.png", title: "Pilar de las Llamas / Cazador de Demonios" },
  { name: "Muichiro Tokito", category: "ESPADA", emoji: "⚔️", anime: "KIMETSU NO YAIBA", image: "https://s4.anilist.co/file/anilistcdn/character/large/b127541-vY8R2s9k0Mh1.png", title: "Pilar de la Niebla / Cazador de Demonios" },
  { name: "Zenitsu Agatsuma", category: "ESPADA", emoji: "⚔️", anime: "KIMETSU NO YAIBA", image: "https://s4.anilist.co/file/anilistcdn/character/large/b127537-ojf3wW4s7JhH.png", title: "Cazador de Demonios / Respiración del Trueno" },
  { name: "Yoriichi Tsugikuni", category: "ESPADA", emoji: "⚔️", anime: "KIMETSU NO YAIBA", image: "https://s4.anilist.co/file/anilistcdn/character/large/b158417-6uR5v0k5f5h3.png", title: "Creador de la Respiración del Sol / Primer Pilar" },
  { name: "Sasuke Uchiha", category: "ESPADA", emoji: "⚔️", anime: "NARUTO", image: "https://s4.anilist.co/file/anilistcdn/character/large/b19-V0Bq7rO7s6U1.png", title: "Último Uchiha / El Apoyo de las Sombras" },
  { name: "Mifune", category: "ESPADA", emoji: "⚔️", anime: "SOUL EATER", image: "https://s4.anilist.co/file/anilistcdn/character/large/b18872-8z4MTTnm8Iln.png", title: "Samurái / Director de Death Weapon Meister Academy" },
  { name: "Asta", category: "ESPADA", emoji: "⚔️", anime: "BLACK CLOVER", image: "https://s4.anilist.co/file/anilistcdn/character/large/b106083-T0x7P7x0h1yN.png", title: "Caballero Mágico / Anti-Magia" },
  { name: "Erza Scarlet", category: "ESPADA", emoji: "⚔️", anime: "FAIRY TAIL", image: "https://s4.anilist.co/file/anilistcdn/character/large/b5-4z4V0d9t6h7N.png", title: "Titania / Maga de Armadura de Fairy Tail" },
  { name: "Kirito", category: "ESPADA", emoji: "⚔️", anime: "SAO", image: "https://s4.anilist.co/file/anilistcdn/character/large/b23631-8z4MTTnm8Iln.png", title: "El Espadachín Negro / Jugador de SAO" },
  { name: "Asuna Yuuki", category: "ESPADA", emoji: "⚔️", anime: "SAO", image: "https://s4.anilist.co/file/anilistcdn/character/large/b23632-5bBIAnku8xlm.png", title: "Flash / Sub-líder de los Caballeros de la Sangre" },
  { name: "Guts", category: "ESPADA", emoji: "⚔️", anime: "BERSERK", image: "https://s4.anilist.co/file/anilistcdn/character/large/b42-1klzM5HFLr1T.png", title: "El Espadachín Negro / Portador de la Espada Dragón" },
  { name: "Griffith", category: "ESPADA", emoji: "⚔️", anime: "BERSERK", image: "https://s4.anilist.co/file/anilistcdn/character/large/b45-4z4V0d9t6h7N.png", title: "Halcón Blanco / Líder de la Banda del Halcón" },
  { name: "Kenshin Himura", category: "ESPADA", emoji: "⚔️", anime: "SAMURAI X", image: "https://s4.anilist.co/file/anilistcdn/character/large/b18-5t8M6B8y8h6.png", title: "Battousai / Samurái Errante" },
  { name: "Hyakkimaru", category: "ESPADA", emoji: "⚔️", anime: "DORORO", image: "https://s4.anilist.co/file/anilistcdn/character/large/b69231-6uR5v0k5f5h3.png", title: "Guerrero sin Cuerpo / Hijo de Daigo" },
  { name: "Levi Ackerman", category: "ESPADA", emoji: "⚔️", anime: "ATTACK ON TITAN", image: "https://s4.anilist.co/file/anilistcdn/character/large/b45628-3yR0Q3rVnX6E.png", title: "Capitán del Escuadrón de Operaciones Especiales" },
  { name: "Mikasa Ackerman", category: "ESPADA", emoji: "⚔️", anime: "ATTACK ON TITAN", image: "https://s4.anilist.co/file/anilistcdn/character/large/b45629-0g6R0R6f7d7N.png", title: "La Mejor Soldado de la Humanidad" },
  { name: "Vergil", category: "ESPADA", emoji: "⚔️", anime: "DEVIL MAY CRY", image: "https://s4.anilist.co/file/anilistcdn/character/large/b132815-8RqC94fG6k2m.png", title: "Hijo de Sparda / El Heraldo de la Tormenta" },
  { name: "Raiden", category: "ESPADA", emoji: "⚔️", anime: "METAL GEAR RISING", image: "https://s4.anilist.co/file/anilistcdn/character/large/b45627-9q8pF4s5q2tD.png", title: "Cyborg Ninja / Ripper" },
  { name: "B2", category: "ESPADA", emoji: "⚔️", anime: "NIER: AUTOMATA", image: "https://s4.anilist.co/file/anilistcdn/character/large/b120117-Xx5x0P9n0v1y.png", title: "YoRHa No.2 Type B / Androide de Batalla" },
  { name: "Saber", category: "ESPADA", emoji: "⚔️", anime: "FATE", image: "https://s4.anilist.co/file/anilistcdn/character/large/b4-5t8M6B8y8h6.png", title: "Rey Arturo / Servant de Clase Saber" },
  { name: "Mugen", category: "ESPADA", emoji: "⚔️", anime: "SAMURAI CHAMPLOO", image: "https://s4.anilist.co/file/anilistcdn/character/large/b562-8RqC94fG6k2m.png", title: "Samurái de Estilo Libre / Vagabundo" },
  { name: "Jinwoo Sung", category: "ESPADA", emoji: "⚔️", anime: "SOLO LEVELING", image: "https://s4.anilist.co/file/anilistcdn/character/large/b164607-1p9Xj5v9S6qN.png", title: "El Cazador Más Fuerte / Monarca de las Sombras" },
  { name: "Hakumen", category: "ESPADA", emoji: "⚔️", anime: "BLAZBLUE", image: "https://s4.anilist.co/file/anilistcdn/character/large/b13724-6uR5v0k5f5h3.png", title: "Héroe Blanco / Guerrero Legendario" },
  { name: "Sesshomaru", category: "ESPADA", emoji: "⚔️", anime: "INUYASHA", image: "https://s4.anilist.co/file/anilistcdn/character/large/b434-L1SNOdzJ5g9d.png", title: "Demonio de la Nieve / Hermano Mayor de Inuyasha" },
  { name: "inuyasha", category: "ESPADA", emoji: "⚔️", anime: "INUYASHA", image: "https://s4.anilist.co/file/anilistcdn/character/large/b433-T0x7P7x0h1yN.png", title: "Hijo de un Demonio y Humana / Portador de Tessaiga" },
  { name: "Ragna the Bloodedge", category: "ESPADA", emoji: "⚔️", anime: "BLAZBLUE", image: "https://s4.anilist.co/file/anilistcdn/character/large/b13715-ojf3wW4s7JhH.png", title: "Portador de la Azure Grimoire / Rebelde" },
  { name: "Noctis Lucis Caelum", category: "ESPADA", emoji: "⚔️", anime: "FINAL FANTASY XV", image: "https://s4.anilist.co/file/anilistcdn/character/large/b86655-5t8M6B8y8h6.png", title: "Rey de Lucis / Portador del Cristal" },
  { name: "Dante", category: "ESPADA", emoji: "⚔️", anime: "DEVIL MAY CRY", image: "https://s4.anilist.co/file/anilistcdn/character/large/b132813-ojf3wW4s7JhH.png", title: "Cazador de Demonios / Hijo de Sparda" },
  { name: "Rimuru Tempest", category: "ESPADA", emoji: "⚔️", anime: "That Time I Got Reincarnated as a Slime", image: "https://s4.anilist.co/file/anilistcdn/character/large/b120569-Xx5x0P9n0v1y.png", title: "Señor de la Tempestad / Slime Legendario" },
  { name: "Inosuke Hashibira", category: "ESPADA", emoji: "⚔️", anime: "Demon Slayer: Kimetsu no Yaiba", image: "https://s4.anilist.co/file/anilistcdn/character/large/b127539-vY8R2s9k0Mh1.png", title: "Cazador de Demonios / Respiración de la Bestia" },
  { name: "Escanor", category: "ESPADA", emoji: "⚔️", anime: "The Seven Deadly Sins: Revival of the Commandments", image: "https://s4.anilist.co/file/anilistcdn/character/large/b87051-L1SNOdzJ5g9d.png", title: "Lion's Sin of Pride / El Hombre Más Fuerte" },
  { name: "Sho Kusakabe", category: "ESPADA", emoji: "⚔️", anime: "Fire Force", image: "https://s4.anilist.co/file/anilistcdn/character/large/b106063-6uR5v0k5f5h3.png", title: "Capitán de la Compañía 8 / Hermano de Shinra" },

  // MAGIA - 38 personajes
  { name: "Yuta Okkotsu", category: "MAGIA", emoji: "✨", anime: "JUJUTSU KAISEN", image: "https://s4.anilist.co/file/anilistcdn/character/large/b207947-6uR5v0k5f5h3.png", title: "Hechicero Especial / Portador de Rika" },
  { name: "Satoru Gojo", category: "MAGIA", emoji: "✨", anime: "JUJUTSU KAISEN", image: "https://s4.anilist.co/file/anilistcdn/character/large/b127563-8RqC94fG6k2m.png", title: "El Hechicero Más Fuerte / Infinito" },
  { name: "Megumi Fushiguro", category: "MAGIA", emoji: "✨", anime: "JUJUTSU KAISEN", image: "https://s4.anilist.co/file/anilistcdn/character/large/b131411-T0x7P7x0h1yN.png", title: "Usuario de la Sombra Diez / Heredero Zenin" },
  { name: "Ryomen Sukuna", category: "MAGIA", emoji: "✨", anime: "Jujutsu Kaisen", image: "https://s4.anilist.co/file/anilistcdn/character/large/b131409-L1SNOdzJ5g9d.png", title: "El Rey de las Maldiciones / Dedo de Sukuna" },
  { name: "Suguru Geto (kenjaku?)", category: "MAGIA", emoji: "✨", anime: "JUJUTSU KAISEN", image: "https://s4.anilist.co/file/anilistcdn/character/large/b131410-ojf3wW4s7JhH.png", title: "Hechicero Maldito / Usuario del Espíritu Maldito" },
  { name: "Mahito", category: "MAGIA", emoji: "✨", anime: "JUJUTSU KAISEN", image: "https://s4.anilist.co/file/anilistcdn/character/large/b149175-8z4MTTnm8Iln.png", title: "Espíritu Maldito de Grado Especial" },
  { name: "Choso", category: "MAGIA", emoji: "✨", anime: "JUJUTSU KAISEN", image: "https://s4.anilist.co/file/anilistcdn/character/large/b182473-5t8M6B8y8h6.png", title: "Incarnación de la Muerte / Hermano Mayor" },
  { name: "Megumin", category: "MAGIA", emoji: "💥", anime: "KONOSUBA -God's blessing on this wonderful world!", image: "https://s4.anilist.co/file/anilistcdn/character/large/b70971-5t8M6B8y8h6.png", title: "Archimaga de Explosión / Crimson Demon" },
  { name: "Frieren", category: "MAGIA", emoji: "✨", anime: "Frieren: Beyond Journey's End", image: "https://s4.anilist.co/file/anilistcdn/character/large/bb212309-6uR5v0k5f5h3.png", title: "Maga Élfica / Viajera Inmortal" },
  { name: "Fern", category: "MAGIA", emoji: "✨", anime: "Frieren: Beyond Journey's End", image: "https://s4.anilist.co/file/anilistcdn/character/large/b212310-8RqC94fG6k2m.png", title: "Aprendiz de Frieren / Maga de Batalla" },
  { name: "Portgas D. Ace", category: "MAGIA", emoji: "🔥", anime: "ONE PIECE", image: "https://s4.anilist.co/file/anilistcdn/character/large/b52-3yR0Q3rVnX6E.png", title: "Puño de Fuego / Hijo de Gol D. Roger" },
  { name: "Aokiji", category: "MAGIA", emoji: "❄️", anime: "ONE PIECE", image: "https://s4.anilist.co/file/anilistcdn/character/large/b51-4z4V0d9t6h7N.png", title: "El Caminante Solitario / Ex-Almirante" },
  { name: "Akainu", category: "MAGIA", emoji: "🔥", anime: "ONE PIECE", image: "https://s4.anilist.co/file/anilistcdn/character/large/b50-5t8M6B8y8h6.png", title: "Sakazuki / Almirante de la Marina" },
  { name: "Kizaru", category: "MAGIA", emoji: "✨", anime: "ONE PIECE", image: "https://s4.anilist.co/file/anilistcdn/character/large/b49-6uR5v0k5f5h3.png", title: "Almirante de la Luz / Usuario de la Pika Pika no Mi" },
  { name: "Boa Hancock", category: "MAGIA", emoji: "💕", anime: "ONE PIECE", image: "https://s4.anilist.co/file/anilistcdn/character/large/h61-Mc8x0s5T1p9X.png", title: "Emperatriz Pirata / Usuario de la Mero Mero no Mi" },
  { name: "Eustass Kid", category: "MAGIA", emoji: "🧲", anime: "ONE PIECE", image: "https://s4.anilist.co/file/anilistcdn/character/large/b62-1r5qor5ZBE1X.png", title: "Capitán Pirata / Usuario de la Jiki Jiki no Mi" },
  { name: "Blackbeard", category: "MAGIA", emoji: "🌑", anime: "ONE PIECE", image: "https://s4.anilist.co/file/anilistcdn/character/large/b62-1r5qor5ZBE1X.png", title: "Marshall D. Teach / Emperador de la Oscuridad" },
  { name: "Perona", category: "MAGIA", emoji: "👻", anime: "One Piece", image: "https://s4.anilist.co/file/anilistcdn/character/large/b8172-8z4MTTnm8Iln.png", title: "Princesa de los Fantasmas / Usuario de la Horo Horo no Mi" },
  { name: "Charlotte Katakuri", category: "MAGIA", emoji: "🍩", anime: "ONE PIECE", image: "https://s4.anilist.co/file/anilistcdn/character/large/b141067-6uR5v0k5f5h3.png", title: "Comandante Dulce / Usuario de la Mochi Mochi no Mi" },
  { name: "Milim Nava", category: "MAGIA", emoji: "✨", anime: "Tensei shitara Slime Datta Ken", image: "https://s4.anilist.co/file/anilistcdn/character/large/b120569-Xx5x0P9n0v1y.png", title: "Destructor / Demonio Dragon" },
  { name: "Diablo", category: "MAGIA", emoji: "✨", anime: "That Time I Got Reincarnated as a Slime", image: "https://s4.anilist.co/file/anilistcdn/character/large/b129072-8RqC94fG6k2m.png", title: "Primordial Negro / Sirviente de Rimuru" },
  { name: "Lucy Heartfilia", category: "MAGIA", emoji: "✨", anime: "Fairy Tail", image: "https://s4.anilist.co/file/anilistcdn/character/large/b6-5t8M6B8y8h6.png", title: "Maga de Espíritus Celestiales" },
  { name: "Zeref", category: "MAGIA", emoji: "🖤", anime: "Fairy Tail", image: "https://s4.anilist.co/file/anilistcdn/character/large/b14002-ojf3wW4s7JhH.png", title: "El Mago Negro / Creador de los Etherious" },
  { name: "Noelle Silva", category: "MAGIA", emoji: "✨", anime: "Black Clover", image: "https://s4.anilist.co/file/anilistcdn/character/large/b106082-8RqC94fG6k2m.png", title: "Maga de Agua / Casa Silva" },
  { name: "Tatsumaki", category: "MAGIA", emoji: "🌪️", anime: "one punch man", image: "https://s4.anilist.co/file/anilistcdn/character/large/b73977-Xx5x0P9n0v1y.png", title: "Tornado del Terror / Clase S Rank 2" },
  { name: "Madoka Kaname", category: "MAGIA", emoji: "✨", anime: "Mahou Shoujo Madoka★Magica", image: "https://s4.anilist.co/file/anilistcdn/character/large/b38028-8z4MTTnm8Iln.png", title: "Puella Magi / Dios de la Ley de los Ciclos" },
  { name: "Homura Akemi", category: "MAGIA", emoji: "✨", anime: "Mahou Shoujo Madoka★Magica", image: "https://s4.anilist.co/file/anilistcdn/character/large/b38029-0g6R0R6f7d7N.png", title: "Puella Magi del Tiempo / Protectora de Madoka" },
  { name: "Mami Tomoe", category: "MAGIA", emoji: "✨", anime: "Mahou Shoujo Madoka★Magica", image: "https://s4.anilist.co/file/anilistcdn/character/large/b38030-ojf3wW4s7JhH.png", title: "Puella Magi de los Mosquetes / Mentora" },
  { name: "Ainz Ooal Gown", category: "MAGIA", emoji: "💀", anime: "Overlord", image: "https://s4.anilist.co/file/anilistcdn/character/large/b70663-6uR5v0k5f5h3.png", title: "Señor Supremo de la Gran Tumba de Nazarick" },
  { name: "Emilia", category: "MAGIA", emoji: "✨", anime: "Re zero", image: "https://s4.anilist.co/file/anilistcdn/character/large/b71175-T0x7P7x0h1yN.png", title: "Media Elfa / Candidata a Reina" },
  { name: "Beatrice", category: "MAGIA", emoji: "✨", anime: "Re zero", image: "https://s4.anilist.co/file/anilistcdn/character/large/b71176-ojf3wW4s7JhH.png", title: "Espíritu Artificial / Biblioteca de la Intimidad" },
  { name: "Roxy Migurdia", category: "MAGIA", emoji: "✨", anime: "Mushoku Tensei: Isekai Ittara Honki Dasu", image: "https://s4.anilist.co/file/anilistcdn/character/large/b170735-5t8M6B8y8h6.png", title: "Maga Acuática / Maestra de Rudeus" },
  { name: "Rudeus Greyrat", category: "MAGIA", emoji: "✨", anime: "Mushoku Tensei: Isekai Ittara Honki Dasu", image: "https://s4.anilist.co/file/anilistcdn/character/large/b170737-6uR5v0k5f5h3.png", title: "Mago de Rango Santo / Reencarnado" },
  { name: "Anos Voldigoad", category: "MAGIA", emoji: "✨", anime: "The Misfit of Demon King Academy", image: "https://s4.anilist.co/file/anilistcdn/character/large/b138669-Xx5x0P9n0v1y.png", title: "Rey Demonio de la Tirania / El Inadaptado" },
  { name: "Howl", category: "MAGIA", emoji: "✨", anime: "Howl's Moving Castle", image: "https://s4.anilist.co/file/anilistcdn/character/large/b5850-5t8M6B8y8h6.png", title: "Mago de la Tierra Desolada / Castillo Ambulante" },
  { name: "Sailor Moon", category: "MAGIA", emoji: "🌙", anime: "Sailor Moon", image: "https://s4.anilist.co/file/anilistcdn/character/large/b390-8RqC94fG6k2m.png", title: "Usagi Tsukino / Guardiana del Amor y la Justicia" },
  { name: "Sailor Mars", category: "MAGIA", emoji: "🔥", anime: "Sailor Moon", image: "https://s4.anilist.co/file/anilistcdn/character/large/b391-ojf3wW4s7JhH.png", title: "Rei Hino / Guardiana del Fuego y la Guerra" },
  { name: "Sailor Mercury", category: "MAGIA", emoji: "💧", anime: "Sailor Moon", image: "https://s4.anilist.co/file/anilistcdn/character/large/b391-ojf3wW4s7JhH.png", title: "Ami Mizuno / Guardiana del Agua y la Sabiduría" },
  { name: "Gilgamesh", category: "MAGIA", emoji: "✨", anime: "Fate/Zero", image: "https://s4.anilist.co/file/anilistcdn/character/large/b31-5bBIAnku8xlm.png", title: "Rey de los Héroes / Archer de la Cuarta Guerra" }
];

const categories = ['MELEE', 'ESPADA', 'MAGIA'];

// Exportar para Node.js (si es necesario)
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { candidates, categories };
}
