/* eslint-disable */
/**
 * Generated `api` utility for working with Convex functions.
 *
 * This file is automatically generated by Convex.
 */
import type { ApiFromModules } from "convex/api";
import type * as votes from "../votes.js";

declare const fullApi: ApiFromModules<{
  votes: typeof votes;
}>;
export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
